# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 15:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entreprises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarque', models.TextField(blank=True, null=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='horaires',
            name='jour',
            field=models.CharField(choices=[('sa', 'samedi'), ('di', 'dimanche'), ('lu', 'lundi'), ('ma', 'mardi')], max_length=3),
        ),
    ]
